### PR TITLE
Put the license into COPYING

### PR DESCRIPTION
**Pull request by tarsius**
Replace the permission statement in COPYING with the actual license
and remove the now redundant COPYING-GPL-3.  This helps tools that
extract licensing information.  Such tools do not look for a file
COPYING-GPL-3, but do check the contents of COPYING.

### CODE REVIEW

**Comment by tarsius** [comment]
Friendly ping!

**Comment by tarsius** [comment]
Pong?

**Comment by tarsius** [comment]
Giving up. For the benefit of the Emacsmirror the license is now hardcoded in license extraction code in `elx.el`.

**Comment by tarsius** [comment]
Giving up. For the benefit of the Emacsmirror the license is now hardcoded in license extraction code in `elx.el`.

**Comment by tarsius** [comment]
@purcell are you okay with me removing this from Melpa? It has 1182 downloads and was last updated in 2015.

@tjim if this specified the license in one of the common ways we support, then we would be happy to keep this in Melpa and the Emacsmirror.

Re https://github.com/purcell/package-lint/issues/83

**Comment by purcell** [comment]
> are you okay with me removing this from Melpa? It has 1182 downloads and was last updated in 2015.

Sure.

**Comment by tarsius** [comment]
I have contacted him by email and will wait for a few more days.

@tjim I am unable to reopen this pull-request because I have already deleted the repository from which it came last year. While I am not sure about that, you probably cannot reopen this either.

Even if that is the case you can still merge this change in less than a minute:

```
git clone git@github.com:tjim/nevermore.git
cd nevermore
git fetch origin refs/pull/8/head
git merge FETCH_HEAD
git push
```

**Pull request closed without merging**
